In [1]:
import tensorflow as tf
from CNN_encoder import CNN_Encoder
import os
from configs import argHandler
from tokenizer_wrapper import TokenizerWrapper
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
from caption_evaluation import get_evalutation_scores
from utility import get_enqueuer
import numpy as np
from PIL import Image
import json
import time
from gpt2.gpt2_model import TFGPT2LMHeadModel
import pandas as pd
from tqdm import tqdm
from skimage.transform import resize
from tensorflow.keras.preprocessing.image import img_to_array,load_img
import re
import pickle

105


In [2]:
from generator import AugmentedImageSequence

In [3]:
FLAGS = argHandler()
FLAGS.setDefaults()

In [4]:
tokenizer_wrapper = TokenizerWrapper(FLAGS.all_data_csv, FLAGS.csv_label_columns[0],
                                         FLAGS.max_sequence_length, FLAGS.tokenizer_vocab_size)

Tokenizing dataset..
number of tokens: {'UNK': 1, 'no': 2, 'the': 3, 'is': 4, 'are': 5, 'normal': 6, 'startseq': 7, 'endseq': 8, 'xxxx': 9, 'of': 10, 'and': 11, 'acute': 12, 'pleural': 13, 'or': 14, 'pneumothorax': 15, 'effusion': 16, 'there': 17, 'heart': 18, 'lungs': 19, 'size': 20, 'focal': 21, 'clear': 22, 'pulmonary': 23, 'within': 24, 'in': 25, 'disease': 26, 'cardiopulmonary': 27, 'limits': 28, 'right': 29, 'left': 30, 'consolidation': 31, 'abnormality': 32, 'with': 33, 'silhouette': 34, 'airspace': 35, 'mediastinal': 36, 'lung': 37, 'stable': 38, 'cardiomediastinal': 39, '1': 40, 'changes': 41, 'chest': 42, 'findings': 43, 'spine': 44, 'evidence': 45, 'a': 46, 'mild': 47, 'unremarkable': 48, 'mediastinum': 49, 'contour': 50, 'thoracic': 51, 'without': 52, 'structures': 53, 'for': 54, 'to': 55, 'contours': 56, 'bony': 57, 'effusions': 58, 'seen': 59, 'atelectasis': 60, 'degenerative': 61, 'opacity': 62, 'large': 63, 'upper': 64, 'calcified': 65, 'lobe': 66, 'cardiac': 67, '2': 6

In [5]:
step_n=1

In [6]:
def get_sen(FLAGS, encoder, decoder, tokenizer_wrapper, images):
    global step_n
    visual_features, tags_embeddings = encoder(images)
    dec_input = tf.expand_dims(tokenizer_wrapper.GPT2_encode("startseq", pad=False), 0)
    # dec_input = tf.tile(dec_input,[images.shape[0],1])
    num_beams = FLAGS.beam_width

    visual_features = tf.tile(visual_features, [num_beams, 1, 1])
    tags_embeddings = tf.tile(tags_embeddings, [num_beams, 1, 1])

    tokens = decoder.generate(dec_input, max_length=FLAGS.max_sequence_length, num_beams=num_beams, min_length=3,
                              eos_token_ids=tokenizer_wrapper.GPT2_eos_token_id(), no_repeat_ngram_size=0,
                              visual_features=visual_features,
                              tags_embedding=tags_embeddings, do_sample=False, early_stopping=True)
    sentence = tokenizer_wrapper.GPT2_decode(tokens[0])
    sentence = tokenizer_wrapper.filter_special_words(sentence)
    step_n += 1
    return sentence

In [7]:
pattern = re.compile(r'"([^"]*)"')


In [8]:
actual = []
predicted = []

In [9]:
def get_sentence(enqueuer, steps, FLAGS, encoder, decoder, tokenizer_wrapper, name='Test set', verbose=True,
                      write_json=True, write_images=False, test_mode=False):
    
    if not enqueuer.is_running():
        enqueuer.start(workers=FLAGS.generator_workers, max_queue_size=FLAGS.generator_queue_length)
    csv_dict = {"image_path": [], "real": [], "prediction": []}
    generator = enqueuer.get()
    for batch in tqdm(list(range(steps))):
        images, target, img_path = next(generator)
        predicted_sentence = get_sen(FLAGS, encoder, decoder, tokenizer_wrapper,images)
        target_sentence = tokenizer_wrapper.GPT2_decode(target[0])
        match = pattern.search(predicted_sentence)
        if match:
            pred = match.group(1)
        else:
            pred="No sentence found"
        actual.append(target_sentence)
        predicted.append(pred)
        

        

    

In [10]:
deploy_enqueuer, deploy_steps = get_enqueuer("deploy.csv", 1, FLAGS, tokenizer_wrapper)
deploy_enqueuer.start(workers=1, max_queue_size=8)

encoder = CNN_Encoder('pretrained_visual_model', FLAGS.visual_model_name, FLAGS.visual_model_pop_layers,
                          FLAGS.encoder_layers, FLAGS.tags_threshold, num_tags=len(FLAGS.tags))

decoder = TFGPT2LMHeadModel.from_pretrained('distilgpt2', from_pt=True, resume_download=True)

optimizer = tf.keras.optimizers.Adam()

ckpt = tf.train.Checkpoint(encoder=encoder,
                               decoder=decoder,
                               optimizer=optimizer)

ckpt_manager = tf.train.CheckpointManager(ckpt, FLAGS.ckpt_path, max_to_keep=1)

Loaded model from disk
[(None, 105), (None, 7, 7, 1024)]
GPT2Config {
  "_num_labels": 1,
  "activation_function": "gelu_new",
  "architectures": [
    "GPT2LMHeadModel"
  ],
  "attn_pdrop": 0.1,
  "bos_token_id": 50256,
  "do_sample": false,
  "embd_pdrop": 0.1,
  "eos_token_id": 50256,
  "eos_token_ids": 0,
  "finetuning_task": null,
  "id2label": {
    "0": "LABEL_0"
  },
  "initializer_range": 0.02,
  "is_decoder": false,
  "label2id": {
    "LABEL_0": 0
  },
  "layer_norm_epsilon": 1e-05,
  "length_penalty": 1.0,
  "max_length": 20,
  "model_type": "gpt2",
  "n_ctx": 1024,
  "n_embd": 768,
  "n_head": 12,
  "n_layer": 6,
  "n_positions": 1024,
  "num_beams": 1,
  "num_labels": 2,
  "num_return_sequences": 1,
  "output_attentions": false,
  "output_hidden_states": false,
  "output_past": true,
  "pad_token_id": 0,
  "pruned_heads": {},
  "repetition_penalty": 1.0,
  "resid_pdrop": 0.1,
  "summary_activation": null,
  "summary_first_dropout": 0.1,
  "summary_proj_to_labels": true,
 

In [11]:
print(ckpt_manager.latest_checkpoint)

./checkpoints/CDGPT2/ckpt-27


In [12]:
if ckpt_manager.latest_checkpoint:
    start_epoch = int(ckpt_manager.latest_checkpoint.split('-')[-1])
    ckpt.restore(ckpt_manager.latest_checkpoint)
    print("Restored from checkpoint: {}".format(ckpt_manager.latest_checkpoint))

Restored from checkpoint: ./checkpoints/CDGPT2/ckpt-27


In [13]:
get_sentence(deploy_enqueuer, deploy_steps, FLAGS, encoder, decoder, tokenizer_wrapper, write_images=True, test_mode=True)

  0%|          | 0/54 [00:00<?, ?it/s]


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[0.14563376]
  [0.25019544]
  [0.68884444]
  [0.08255053]
  [0.05429024]
  [0.03624111]
  [0.380957  ]
  [0.33621037]
  [0.0943265 ]
  [0.2593426 ]
  [0.02077344]
  [0.09621164]
  [0.06612301]
  [0.29921317]
  [0.04234526]
  [0.01489362]
  [0.00206524]
  [0.04459551]
  [0.07820541]
  [0.37188056]
  [0.00216144]
  [0.02772549]
  [0.01681116]
  [0.0762

  2%|▏         | 1/54 [00:39<35:17, 39.95s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[0.03966999]
  [0.32395017]
  [0.39470607]
  [0.0334183 ]
  [0.0510104 ]
  [0.02662587]
  [0.14379811]
  [0.10753283]
  [0.0150581 ]
  [0.06105259]
  [0.0248833 ]
  [0.02576765]
  [0.03973651]
  [0.3500988 ]
  [0.05138326]
  [0.03185147]
  [0.03265715]
  [0.11803406]
  [0.12641257]
  [0.10100353]
  [0.02745596]
  [0.26718158]
  [0.10924426]
  [0.21599668]
  [0.38317943]
  [0.10549873]
  [0.19766167]
  [0.33975506]
  [0.29878378]
  [0.04889011]
  [0.06259638]
  [0.11609876]
  [0.06917369]
  [0.01808032]
  [0.04189292]
  [0.02093565]
  [0.02524951]
  [0.01152849]
  [0.01772019]
  [0.03333512]
  [0.00922152]
  [0.0717389 ]
  [0.03658578]
  [0.01862952]
  [0.01380023]
  [0.01148278]
  [0.01503375]
  [0.02462226]
  [0.04518524]
  [0.06222972]
  [0.0769833 ]
  [0.02368647]
  [0.05227885]
  [0.00704774]
  [0.05016652]
  [0.04095563]
  [0.0

  4%|▎         | 2/54 [01:18<34:17, 39.57s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[0.4270842 ]
  [0.16526651]
  [0.13976413]
  [0.08043009]
  [0.03422552]
  [0.00888017]
  [0.03702495]
  [0.01333988]
  [0.00776067]
  [0.03410193]
  [0.00291464]
  [0.01915702]
  [0.02043447]
  [0.07860321]
  [0.01953599]
  [0.0036543 ]
  [0.00122964]
  [0.05750635]
  [0.06792343]
  [0.01684755]
  [0.00170603]
  [0.0327324 ]
  [0.01840872]
  [0.12500629]
  [0.07276288]
  [0.01458979]
  [0.16555676]
  [0.1483429 ]
  [0.02449241]
  [0.00682023]
  [0.01069376]
  [0.0056935 ]
  [0.01351175]
  [0.00433764]
  [0.0158689 ]
  [0.01592633]
  [0.00274625]
  [0.00054428]
  [0.00792721]
  [0.00354853]
  [0.00331199]
  [0.02774662]
  [0.00705907]
  [0.00169882]
  [0.00487766]
  [0.01049739]
  [0.01174882]
  [0.00436515]
  [0.01631793]
  [0.03519666]
  [0.01645494]
  [0.01582861]
  [0.02310675]
  [0.01011026]
  [0.02411324]
  [0.0279206 ]
  [0.0

  6%|▌         | 3/54 [01:58<33:37, 39.55s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[6.0153270e-01]
  [1.2719470e-01]
  [1.6743177e-01]
  [1.5239897e-01]
  [3.4128845e-02]
  [2.6361883e-02]
  [2.4614096e-02]
  [1.3845623e-02]
  [6.1071515e-03]
  [3.0950665e-02]
  [6.8932772e-04]
  [1.3292313e-02]
  [1.0359794e-02]
  [7.2891057e-02]
  [2.1972597e-02]
  [1.9674003e-03]
  [9.3714640e-05]
  [3.9401233e-02]
  [3.2663345e-02]
  [2.9526949e-02]
  [1.3008714e-04]
  [2.3213029e-03]
  [1.3574868e-02]
  [8.8560760e-02]
  [6.5952837e-03]
  [1.3835669e-02]
  [1.1828768e-01]
  [1.0478330e-01]
  [1.4814138e-03]
  [9.4583631e-04]
  [7.5807571e-03]
  [3.5808086e-03]
  [7.8854859e-03]
  [5.4958463e-04]
  [3.4365654e-03]
  [8.1052184e-03]
  [2.8946996e-04]
  [1.2549758e-04]
  [4.4122338e-03]
  [2.0660460e-03]
  [1.4534295e-03]
  [1.9118279e-02]
  [5.4760873e-03]
  [2.5659800e-03]
  [5.9136450e-03]
  [1.6543865e-03]
  [3.0004084e-03]


  7%|▋         | 4/54 [02:37<32:55, 39.51s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[0.2823921 ]
  [0.15881336]
  [0.4420388 ]
  [0.06482318]
  [0.02989677]
  [0.01790398]
  [0.09553877]
  [0.12701005]
  [0.0075455 ]
  [0.16836506]
  [0.00201911]
  [0.01200321]
  [0.02050242]
  [0.24975249]
  [0.02650365]
  [0.00229096]
  [0.00048873]
  [0.02435043]
  [0.04855388]
  [0.15462774]
  [0.00068316]
  [0.00630152]
  [0.00609949]
  [0.04835546]
  [0.01905602]
  [0.00657859]
  [0.05050144]
  [0.17644116]
  [0.00259382]
  [0.00451899]
  [0.09408671]
  [0.00789896]
  [0.00395742]
  [0.0015102 ]
  [0.00570962]
  [0.03847718]
  [0.01479605]
  [0.00120685]
  [0.11143053]
  [0.02201384]
  [0.09530455]
  [0.02015096]
  [0.00366583]
  [0.00676844]
  [0.02955425]
  [0.02684829]
  [0.02564323]
  [0.01814628]
  [0.08498621]
  [0.02977559]
  [0.10109055]
  [0.01911801]
  [0.05013064]
  [0.2199376 ]
  [0.01350772]
  [0.01898524]
  [0.0

  9%|▉         | 5/54 [03:16<32:07, 39.34s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[4.12496626e-02]
  [4.97461885e-01]
  [8.02421451e-01]
  [4.60944474e-02]
  [2.06252903e-01]
  [5.02751172e-02]
  [5.48007548e-01]
  [1.14386320e-01]
  [1.38220072e-01]
  [1.96183026e-01]
  [6.20152354e-02]
  [2.82790959e-02]
  [1.02219284e-01]
  [3.26173812e-01]
  [3.67333889e-02]
  [6.46966696e-03]
  [6.37382269e-04]
  [1.06225908e-02]
  [1.06065243e-01]
  [1.17798775e-01]
  [6.33835793e-04]
  [1.35829747e-02]
  [6.13455176e-02]
  [3.12580466e-02]
  [3.33207548e-02]
  [5.35525978e-02]
  [3.20615470e-02]
  [1.21276706e-01]
  [5.32919466e-02]
  [3.90365124e-02]
  [7.95954466e-03]
  [1.01307929e-02]
  [3.24018896e-02]
  [1.69612169e-02]
  [1.10602975e-02]
  [2.21816301e-02]
  [3.88573706e-02]
  [6.87675178e-02]
  [3.09729576e-02]
  [1.88041061e-01]
  [1.52164698e-02]
  [3.11421156e-02]
  [8.93339515e-03]
  [1.33510977e-01]
  [6.13792

 11%|█         | 6/54 [03:55<31:22, 39.22s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[1.37730122e-01]
  [1.04564935e-01]
  [1.68469280e-01]
  [2.87100971e-02]
  [1.66228414e-02]
  [8.51175189e-03]
  [2.61757970e-02]
  [1.61254406e-02]
  [6.16687536e-03]
  [1.81030035e-02]
  [4.52122092e-03]
  [5.10281324e-02]
  [2.18042433e-02]
  [6.49559200e-02]
  [2.10226178e-02]
  [8.83191824e-03]
  [9.90658998e-03]
  [1.59858227e-01]
  [7.09181130e-02]
  [1.80314183e-02]
  [8.42666626e-03]
  [3.00677180e-01]
  [8.14089179e-03]
  [3.30814779e-01]
  [4.12492812e-01]
  [1.13106668e-02]
  [2.41134763e-01]
  [3.47207367e-01]
  [4.34027672e-01]
  [2.34088004e-02]
  [1.56051517e-02]
  [2.98072696e-02]
  [9.05245841e-02]
  [1.18378699e-02]
  [3.61215472e-02]
  [7.34069943e-03]
  [1.12900138e-03]
  [5.03838062e-04]
  [2.15846300e-03]
  [2.50792503e-03]
  [8.13215971e-04]
  [3.23840976e-02]
  [1.35734975e-02]
  [1.39537454e-03]
  [3.46636

 13%|█▎        | 7/54 [04:35<30:59, 39.56s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[8.99112225e-01]
  [3.07236016e-02]
  [2.70583630e-02]
  [1.61651969e-02]
  [5.03599644e-03]
  [1.63608789e-03]
  [3.68136168e-03]
  [1.06889009e-03]
  [1.00201368e-03]
  [1.07671022e-02]
  [6.62639650e-05]
  [9.93967056e-04]
  [1.28331780e-03]
  [1.00052655e-02]
  [3.43388319e-03]
  [9.41975086e-05]
  [1.25995507e-06]
  [3.93956900e-03]
  [9.94732976e-03]
  [1.88201666e-03]
  [1.72530235e-06]
  [3.46988440e-04]
  [2.90909410e-03]
  [1.22614801e-02]
  [7.96109438e-04]
  [3.23301554e-03]
  [1.68314576e-02]
  [2.53643394e-02]
  [7.14093447e-04]
  [1.47789717e-04]
  [1.50823593e-03]
  [1.53005123e-04]
  [1.99526548e-04]
  [3.07679176e-04]
  [1.42553449e-03]
  [2.29758024e-03]
  [2.44975090e-04]
  [3.03467950e-05]
  [4.37447429e-03]
  [3.31461430e-04]
  [1.82726979e-03]
  [3.42258811e-03]
  [2.28086114e-03]
  [1.29908323e-04]
  [6.05881

 15%|█▍        | 8/54 [05:16<30:42, 40.05s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[0.12523323]
  [0.1997855 ]
  [0.48261455]
  [0.07687125]
  [0.03742453]
  [0.01453283]
  [0.12933844]
  [0.05463237]
  [0.04485649]
  [0.1827887 ]
  [0.01214999]
  [0.01593181]
  [0.04808843]
  [0.1193507 ]
  [0.0231483 ]
  [0.00184155]
  [0.00434789]
  [0.0396198 ]
  [0.16102946]
  [0.05218345]
  [0.00565732]
  [0.13455454]
  [0.00685096]
  [0.12334269]
  [0.28547156]
  [0.00713313]
  [0.17105171]
  [0.28904325]
  [0.09089753]
  [0.02881747]
  [0.02890477]
  [0.00313041]
  [0.00372759]
  [0.00947401]
  [0.00943676]
  [0.01879385]
  [0.02209577]
  [0.00224578]
  [0.0468438 ]
  [0.01344955]
  [0.04278892]
  [0.04838976]
  [0.01034093]
  [0.0062345 ]
  [0.02239114]
  [0.04747567]
  [0.02474281]
  [0.01568264]
  [0.11946157]
  [0.06684196]
  [0.05560863]
  [0.01507506]
  [0.0720886 ]
  [0.18407297]
  [0.03526667]
  [0.01272792]
  [0.0

 17%|█▋        | 9/54 [05:57<30:06, 40.15s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[9.04170990e-01]
  [2.39570439e-02]
  [1.17108226e-02]
  [3.74493003e-03]
  [1.80289149e-03]
  [1.04647875e-03]
  [1.53288245e-03]
  [1.48147345e-04]
  [5.39064407e-04]
  [2.66748667e-03]
  [1.33831800e-05]
  [6.87807798e-04]
  [7.47233629e-04]
  [3.54951620e-03]
  [1.48335099e-03]
  [1.17763622e-04]
  [2.99433829e-08]
  [2.22340226e-03]
  [1.91107392e-03]
  [4.72366810e-04]
  [5.43420100e-08]
  [5.55022743e-05]
  [3.58662009e-03]
  [8.19268823e-03]
  [1.16970827e-04]
  [4.47010994e-03]
  [1.86180472e-02]
  [2.04506516e-02]
  [9.89532471e-03]
  [1.10525449e-04]
  [1.28537416e-04]
  [6.16745165e-05]
  [4.61995602e-04]
  [1.06978416e-03]
  [5.75333834e-04]
  [2.55763531e-04]
  [1.07195861e-04]
  [4.71324074e-06]
  [1.15923940e-04]
  [1.00986435e-04]
  [7.03422047e-05]
  [2.28989124e-03]
  [1.95088983e-03]
  [2.83903446e-05]
  [9.89220

 19%|█▊        | 10/54 [06:37<29:22, 40.06s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[3.22150677e-01]
  [8.62402618e-02]
  [8.84192586e-02]
  [5.91489673e-02]
  [1.19349658e-02]
  [5.11652231e-03]
  [5.26675582e-03]
  [1.65319443e-03]
  [1.49896741e-03]
  [1.38698518e-02]
  [4.19020653e-04]
  [2.80979276e-03]
  [8.00460577e-03]
  [3.53365839e-02]
  [9.36523080e-03]
  [4.95880842e-04]
  [6.75529242e-04]
  [7.94749260e-02]
  [8.77743959e-02]
  [2.84361839e-03]
  [8.41528177e-04]
  [1.06164932e-01]
  [4.73499298e-03]
  [2.91320026e-01]
  [1.82441026e-01]
  [3.32540274e-03]
  [3.22022080e-01]
  [1.75801307e-01]
  [1.04549825e-02]
  [1.62750483e-03]
  [4.17810678e-03]
  [7.58081675e-04]
  [7.49379396e-04]
  [6.27100468e-04]
  [5.01239300e-03]
  [4.96339798e-03]
  [1.42544508e-04]
  [2.36312226e-05]
  [9.72867012e-04]
  [2.52991915e-04]
  [4.03046608e-04]
  [1.96528137e-02]
  [3.53586674e-03]
  [1.56641006e-04]
  [4.69058

 20%|██        | 11/54 [07:16<28:37, 39.93s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[0.0943706 ]
  [0.2565745 ]
  [0.47810417]
  [0.07160345]
  [0.04568771]
  [0.02286747]
  [0.1676043 ]
  [0.1332156 ]
  [0.03743649]
  [0.13338912]
  [0.02233893]
  [0.10177851]
  [0.04541472]
  [0.266866  ]
  [0.04665008]
  [0.0306704 ]
  [0.02160558]
  [0.11447611]
  [0.10121873]
  [0.18875208]
  [0.02093858]
  [0.09355584]
  [0.05316031]
  [0.23608997]
  [0.18305925]
  [0.05959448]
  [0.19315031]
  [0.32542187]
  [0.11400524]
  [0.03601891]
  [0.06114107]
  [0.08723983]
  [0.12795615]
  [0.01295149]
  [0.04122591]
  [0.04299855]
  [0.01546788]
  [0.00593919]
  [0.02164164]
  [0.03471017]
  [0.01086649]
  [0.04670984]
  [0.02413589]
  [0.01752487]
  [0.03178871]
  [0.01914972]
  [0.01848191]
  [0.0184274 ]
  [0.04997322]
  [0.04814383]
  [0.04110062]
  [0.02482504]
  [0.06754875]
  [0.00724372]
  [0.04009581]
  [0.05410835]
  [0.0

 22%|██▏       | 12/54 [07:56<27:58, 39.97s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[6.2684941e-01]
  [7.7044159e-02]
  [8.8512301e-02]
  [2.3787260e-02]
  [8.3782673e-03]
  [6.8497658e-03]
  [1.5078217e-02]
  [4.1640103e-03]
  [5.0426126e-03]
  [1.2149662e-02]
  [1.3874173e-03]
  [1.8211961e-02]
  [1.1549681e-02]
  [2.3435593e-02]
  [7.6816380e-03]
  [1.4207363e-03]
  [7.0417746e-06]
  [1.5678108e-02]
  [1.9789994e-02]
  [6.2025785e-03]
  [1.1439078e-05]
  [3.3284426e-03]
  [1.8878907e-02]
  [4.3879420e-02]
  [4.7127008e-03]
  [1.4153540e-02]
  [5.2908719e-02]
  [6.8322450e-02]
  [5.5493623e-02]
  [1.4291704e-03]
  [1.4202893e-03]
  [2.2428036e-03]
  [3.8367778e-02]
  [8.9821517e-03]
  [1.1512995e-02]
  [2.0247400e-03]
  [8.9436769e-04]
  [2.5108457e-04]
  [1.5375614e-03]
  [2.8677881e-03]
  [4.1592121e-04]
  [1.3898432e-02]
  [4.7324598e-03]
  [9.9372864e-04]
  [1.9306839e-03]
  [1.3107359e-03]
  [2.0695627e-03]


 24%|██▍       | 13/54 [08:36<27:12, 39.83s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[0.1291045 ]
  [0.20311534]
  [0.2506671 ]
  [0.1083903 ]
  [0.02941793]
  [0.02679092]
  [0.05536419]
  [0.02222174]
  [0.01857772]
  [0.06643906]
  [0.00707322]
  [0.01242775]
  [0.02998382]
  [0.13206953]
  [0.0241181 ]
  [0.00300878]
  [0.00406227]
  [0.08326879]
  [0.17757311]
  [0.03185904]
  [0.0055382 ]
  [0.16621831]
  [0.02733767]
  [0.2674404 ]
  [0.3226211 ]
  [0.02795044]
  [0.33252585]
  [0.29968053]
  [0.05611461]
  [0.00824189]
  [0.00901216]
  [0.00367171]
  [0.00406402]
  [0.00415513]
  [0.00832111]
  [0.0104591 ]
  [0.00354761]
  [0.00086999]
  [0.00866085]
  [0.00423864]
  [0.0050388 ]
  [0.05183128]
  [0.02931252]
  [0.00376549]
  [0.00601494]
  [0.00864631]
  [0.01081085]
  [0.01073611]
  [0.05397677]
  [0.06643733]
  [0.04068303]
  [0.01360866]
  [0.0356276 ]
  [0.0535349 ]
  [0.03334805]
  [0.02478665]
  [0.0

 26%|██▌       | 14/54 [09:15<26:25, 39.63s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[3.7054157e-01]
  [9.4721168e-02]
  [1.9333950e-01]
  [1.0771829e-01]
  [4.1665703e-02]
  [2.7187467e-02]
  [4.1898191e-02]
  [2.6114672e-02]
  [8.7513924e-03]
  [3.3639967e-02]
  [9.5292926e-04]
  [1.2773365e-02]
  [1.5066028e-02]
  [8.8985771e-02]
  [1.2906790e-02]
  [4.6955049e-03]
  [6.0367584e-04]
  [6.5291166e-02]
  [3.7904263e-02]
  [3.5561830e-02]
  [4.6187639e-04]
  [1.1405438e-02]
  [6.7675412e-03]
  [1.7185450e-01]
  [3.1565040e-02]
  [7.6208115e-03]
  [1.7212304e-01]
  [1.3343337e-01]
  [3.0265450e-03]
  [2.0207763e-03]
  [5.8947802e-03]
  [8.1354082e-03]
  [9.4572008e-03]
  [5.2070618e-04]
  [4.7324598e-03]
  [1.1104941e-02]
  [2.6801229e-04]
  [2.4706125e-04]
  [5.8659613e-03]
  [3.6728382e-03]
  [1.1110902e-03]
  [1.3166428e-02]
  [2.5932491e-03]
  [4.9726367e-03]
  [8.9174807e-03]
  [2.1587908e-03]
  [2.4510920e-03]


 28%|██▊       | 15/54 [09:55<25:46, 39.65s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[1.49828792e-01]
  [4.41548258e-01]
  [5.12695253e-01]
  [5.47530353e-02]
  [3.57706726e-01]
  [3.68681252e-02]
  [2.59346038e-01]
  [3.79620790e-02]
  [2.69918442e-02]
  [4.26077247e-02]
  [1.20904148e-02]
  [1.78217888e-02]
  [3.86143327e-02]
  [2.97786057e-01]
  [4.34660017e-02]
  [3.53479385e-03]
  [4.77910042e-04]
  [8.09657574e-03]
  [6.93835616e-02]
  [2.34586298e-02]
  [6.13361597e-04]
  [7.22578168e-03]
  [1.21252894e-01]
  [2.67300010e-02]
  [1.50883794e-02]
  [1.25597626e-01]
  [5.65057397e-02]
  [8.51694345e-02]
  [7.04827905e-03]
  [2.69824862e-02]
  [3.95220518e-03]
  [2.94849277e-03]
  [6.68340921e-03]
  [1.84562802e-03]
  [1.09829009e-02]
  [9.45067406e-03]
  [3.56033444e-03]
  [2.09865272e-02]
  [9.12693143e-03]
  [4.30330038e-02]
  [3.79180908e-03]
  [2.43340433e-02]
  [1.46394670e-02]
  [3.43412161e-02]
  [2.55451

 30%|██▉       | 16/54 [10:34<25:01, 39.52s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[8.84711742e-02]
  [2.13866770e-01]
  [3.69442046e-01]
  [1.51406109e-01]
  [3.72291505e-02]
  [3.93045843e-02]
  [5.90599179e-02]
  [5.13836145e-02]
  [9.02894139e-03]
  [5.08089662e-02]
  [5.72454929e-03]
  [3.05171013e-02]
  [2.38875151e-02]
  [1.66010320e-01]
  [5.60180843e-02]
  [1.20408237e-02]
  [1.65071487e-02]
  [2.02154994e-01]
  [1.65033370e-01]
  [7.34906793e-02]
  [1.53251886e-02]
  [1.63319290e-01]
  [1.28748417e-02]
  [4.32568252e-01]
  [3.22051823e-01]
  [1.19191706e-02]
  [3.57798874e-01]
  [2.55572081e-01]
  [1.67505443e-02]
  [9.48202610e-03]
  [3.36683095e-02]
  [2.72229314e-02]
  [3.04290950e-02]
  [1.49768591e-03]
  [1.38433278e-02]
  [2.75390744e-02]
  [1.44085288e-03]
  [5.62846661e-04]
  [9.58094001e-03]
  [5.00038266e-03]
  [2.65857577e-03]
  [4.09938991e-02]
  [6.10670447e-03]
  [3.99264693e-03]
  [9.93919

 31%|███▏      | 17/54 [11:13<24:22, 39.52s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[8.4041500e-01]
  [6.7020655e-02]
  [4.6563894e-02]
  [1.5934765e-02]
  [1.1006027e-02]
  [1.6389191e-03]
  [8.8047087e-03]
  [2.4318695e-03]
  [9.8767877e-04]
  [1.2155801e-02]
  [1.0266325e-04]
  [1.2986362e-03]
  [1.5462041e-03]
  [2.0617515e-02]
  [5.6556463e-03]
  [1.9246340e-04]
  [3.6809433e-06]
  [2.8265417e-03]
  [1.3001263e-02]
  [2.6808977e-03]
  [4.6315918e-06]
  [4.9990416e-04]
  [5.1770508e-03]
  [7.7904761e-03]
  [1.1771023e-03]
  [5.5463910e-03]
  [1.5661031e-02]
  [2.8273731e-02]
  [1.1795163e-03]
  [3.7091970e-04]
  [1.8514693e-03]
  [4.2530894e-04]
  [6.4304471e-04]
  [4.4518709e-04]
  [1.2016296e-03]
  [2.3003817e-03]
  [5.9157610e-04]
  [1.1721281e-04]
  [4.0133893e-03]
  [1.2066364e-03]
  [1.7818511e-03]
  [5.0718784e-03]
  [2.5342405e-03]
  [2.5123358e-04]
  [1.3966560e-03]
  [1.1815429e-03]
  [2.8520525e-03]


 33%|███▎      | 18/54 [11:52<23:32, 39.24s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[6.7237914e-02]
  [2.0846003e-01]
  [7.3213649e-01]
  [1.5705511e-01]
  [6.6952020e-02]
  [3.0646890e-02]
  [1.1084676e-01]
  [4.8425585e-02]
  [2.6892126e-02]
  [1.8768167e-01]
  [5.0380826e-03]
  [1.4463574e-02]
  [3.3820182e-02]
  [2.2158432e-01]
  [7.0370674e-02]
  [1.6105175e-03]
  [1.1581212e-02]
  [7.6372474e-02]
  [2.2345254e-01]
  [5.3261220e-02]
  [1.2454122e-02]
  [1.1385989e-01]
  [5.0338805e-03]
  [1.8973473e-01]
  [3.2440865e-01]
  [7.1356297e-03]
  [2.4172610e-01]
  [3.3017385e-01]
  [2.6031524e-02]
  [4.8157156e-02]
  [7.6116353e-02]
  [2.1321774e-03]
  [7.4538589e-04]
  [2.1555126e-03]
  [9.4404519e-03]
  [3.9561510e-02]
  [3.2788813e-03]
  [8.3285570e-04]
  [2.4480999e-02]
  [4.5563281e-03]
  [2.5314003e-02]
  [4.8309863e-02]
  [1.6558826e-02]
  [2.9948056e-03]
  [1.1898249e-02]
  [5.1328033e-02]
  [2.5407195e-02]


 35%|███▌      | 19/54 [12:31<22:51, 39.18s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[1.90885544e-01]
  [1.64202511e-01]
  [5.48779547e-01]
  [1.92397535e-01]
  [9.58601832e-02]
  [3.69140506e-02]
  [9.22931135e-02]
  [4.60767448e-02]
  [2.84490883e-02]
  [1.22830153e-01]
  [3.52457166e-03]
  [2.40751803e-02]
  [2.40717530e-02]
  [1.40842527e-01]
  [4.09936309e-02]
  [2.85792351e-03]
  [2.25815177e-03]
  [6.90064132e-02]
  [8.21782649e-02]
  [6.27117455e-02]
  [2.11277604e-03]
  [1.96624994e-02]
  [7.05280900e-03]
  [1.70698225e-01]
  [4.93181944e-02]
  [6.89756870e-03]
  [1.51408911e-01]
  [1.58584386e-01]
  [2.40686536e-03]
  [6.83245063e-03]
  [2.21810937e-02]
  [2.54309177e-03]
  [4.36177850e-03]
  [9.26196575e-04]
  [9.94244218e-03]
  [3.91118824e-02]
  [1.00764632e-03]
  [6.60240650e-04]
  [1.92702413e-02]
  [7.39356875e-03]
  [8.92436504e-03]
  [1.65016949e-02]
  [4.97329235e-03]
  [6.55886531e-03]
  [2.14042

 37%|███▋      | 20/54 [13:10<22:09, 39.10s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[7.16834068e-02]
  [2.10685998e-01]
  [8.50923061e-01]
  [6.33267760e-02]
  [4.11595702e-02]
  [3.18259299e-02]
  [3.80800396e-01]
  [2.82036185e-01]
  [2.04323411e-01]
  [3.33505213e-01]
  [2.44662166e-02]
  [2.34601945e-01]
  [9.29989815e-02]
  [1.96214378e-01]
  [4.52331603e-02]
  [1.67703629e-02]
  [1.36744976e-03]
  [4.18855548e-02]
  [7.65824914e-02]
  [4.43740487e-01]
  [1.42398477e-03]
  [1.88173354e-02]
  [8.92153382e-03]
  [9.94497240e-02]
  [4.04963791e-02]
  [9.97164845e-03]
  [6.97520971e-02]
  [3.41663182e-01]
  [1.06409162e-01]
  [3.61908972e-02]
  [7.04142451e-02]
  [4.24188375e-02]
  [3.01579446e-01]
  [2.13139951e-02]
  [3.36634517e-02]
  [3.98657620e-02]
  [6.38428330e-03]
  [5.66852093e-03]
  [1.61559284e-02]
  [6.76732659e-02]
  [1.29200220e-02]
  [2.51860619e-02]
  [3.70556116e-03]
  [7.45303631e-02]
  [9.56805

 39%|███▉      | 21/54 [13:50<21:39, 39.38s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[0.06554094]
  [0.24653658]
  [0.6038237 ]
  [0.03832245]
  [0.03899595]
  [0.0163773 ]
  [0.28806305]
  [0.16095984]
  [0.1690704 ]
  [0.23348296]
  [0.04109988]
  [0.097123  ]
  [0.11888662]
  [0.19387627]
  [0.03006285]
  [0.01451954]
  [0.00492862]
  [0.05744839]
  [0.09427834]
  [0.22646415]
  [0.0046773 ]
  [0.08999363]
  [0.02919862]
  [0.14671427]
  [0.16164368]
  [0.02899724]
  [0.1243062 ]
  [0.38150638]
  [0.4313206 ]
  [0.06857124]
  [0.03390133]
  [0.02728191]
  [0.2358518 ]
  [0.08708426]
  [0.05816829]
  [0.02620322]
  [0.0404748 ]
  [0.01174054]
  [0.03144473]
  [0.0577662 ]
  [0.02737474]
  [0.03128639]
  [0.01892385]
  [0.04101312]
  [0.04263824]
  [0.02002746]
  [0.01617235]
  [0.01739091]
  [0.03575885]
  [0.07318962]
  [0.04531658]
  [0.01350811]
  [0.05190089]
  [0.00749072]
  [0.06205523]
  [0.01380599]
  [0.0

 41%|████      | 22/54 [14:29<20:59, 39.36s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[2.66734362e-01]
  [1.54107660e-01]
  [1.42341286e-01]
  [1.02332562e-01]
  [1.62137151e-02]
  [1.20450854e-02]
  [1.35386288e-02]
  [1.01851225e-02]
  [1.98930502e-03]
  [1.63136721e-02]
  [7.54147768e-04]
  [6.47714734e-03]
  [1.06394887e-02]
  [9.98327434e-02]
  [1.25624239e-02]
  [2.66042352e-03]
  [4.43607569e-04]
  [7.90780783e-02]
  [7.82080591e-02]
  [1.70633793e-02]
  [6.53296709e-04]
  [4.55400944e-02]
  [2.24080086e-02]
  [2.56364405e-01]
  [7.48870969e-02]
  [1.80298388e-02]
  [3.00078928e-01]
  [1.21236265e-01]
  [1.58280134e-03]
  [1.01083517e-03]
  [4.70644236e-03]
  [3.52272391e-03]
  [9.87425447e-03]
  [2.66581774e-04]
  [4.71785665e-03]
  [6.13752007e-03]
  [2.96473503e-04]
  [7.74457512e-05]
  [2.23335624e-03]
  [1.26048923e-03]
  [5.79297543e-04]
  [2.15430260e-02]
  [2.49668956e-03]
  [1.05848908e-03]
  [1.57848

 43%|████▎     | 23/54 [15:11<20:39, 39.97s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[2.96626985e-01]
  [4.65800166e-02]
  [4.95896637e-02]
  [5.16868532e-02]
  [3.43838334e-03]
  [3.63191962e-03]
  [2.34359503e-03]
  [1.34807825e-03]
  [8.62360001e-04]
  [9.66390967e-03]
  [1.31547451e-04]
  [1.85847282e-03]
  [4.17765975e-03]
  [2.56789923e-02]
  [4.68388200e-03]
  [5.55992126e-04]
  [3.52561474e-04]
  [1.35005385e-01]
  [5.78708351e-02]
  [3.72731686e-03]
  [4.93735075e-04]
  [7.47907460e-02]
  [1.50039792e-03]
  [4.61377442e-01]
  [1.77133501e-01]
  [1.29717588e-03]
  [4.29437220e-01]
  [1.95639819e-01]
  [9.28744674e-03]
  [5.72413206e-04]
  [3.11824679e-03]
  [8.17626715e-04]
  [7.86483288e-04]
  [3.27199697e-04]
  [1.20723248e-03]
  [2.36585736e-03]
  [4.84684278e-05]
  [2.99620956e-06]
  [5.07265329e-04]
  [7.32471453e-05]
  [1.89721584e-04]
  [1.49631500e-02]
  [3.41457129e-03]
  [3.94648741e-05]
  [2.24888

 44%|████▍     | 24/54 [15:50<19:50, 39.67s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[0.07760975]
  [0.1910004 ]
  [0.2762425 ]
  [0.07098264]
  [0.03739989]
  [0.02806601]
  [0.10423017]
  [0.05071184]
  [0.0244692 ]
  [0.0451518 ]
  [0.01151374]
  [0.03772011]
  [0.04013801]
  [0.19901836]
  [0.04670772]
  [0.0126265 ]
  [0.02001214]
  [0.1333096 ]
  [0.14742386]
  [0.06698915]
  [0.01762664]
  [0.33314145]
  [0.00893399]
  [0.30376828]
  [0.45638067]
  [0.00861505]
  [0.32351822]
  [0.44373202]
  [0.50792444]
  [0.05066195]
  [0.0227268 ]
  [0.02770871]
  [0.05089924]
  [0.03140423]
  [0.02712211]
  [0.01788813]
  [0.01076469]
  [0.00213361]
  [0.011244  ]
  [0.00846773]
  [0.00642672]
  [0.05759171]
  [0.030729  ]
  [0.0057686 ]
  [0.0103583 ]
  [0.01900765]
  [0.01652873]
  [0.00894237]
  [0.05059725]
  [0.05494475]
  [0.02880609]
  [0.01212117]
  [0.02752379]
  [0.01093102]
  [0.04777449]
  [0.0240505 ]
  [0.0

 46%|████▋     | 25/54 [16:28<19:00, 39.33s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[8.5255837e-01]
  [3.6375701e-02]
  [2.7347326e-02]
  [3.3982068e-02]
  [4.2712688e-03]
  [3.2331944e-03]
  [2.3412406e-03]
  [1.2279153e-03]
  [2.2438169e-04]
  [5.9534013e-03]
  [5.3793981e-05]
  [6.9731474e-04]
  [1.2305081e-03]
  [2.0585030e-02]
  [6.4960718e-03]
  [1.7115474e-04]
  [8.3810846e-06]
  [1.3645798e-02]
  [2.3113489e-02]
  [1.5795529e-03]
  [9.6160566e-06]
  [3.6357045e-03]
  [1.8710792e-03]
  [4.1437835e-02]
  [5.8380365e-03]
  [1.6667247e-03]
  [5.1263660e-02]
  [4.9558908e-02]
  [2.2964180e-03]
  [1.9946694e-04]
  [3.2396913e-03]
  [7.6612830e-04]
  [3.8051605e-04]
  [4.2465329e-04]
  [1.6192794e-03]
  [1.9166470e-03]
  [1.8024445e-04]
  [1.6431744e-05]
  [2.9654205e-03]
  [2.4008751e-04]
  [9.6052885e-04]
  [9.8550022e-03]
  [2.1179914e-03]
  [4.2383181e-05]
  [4.1469932e-04]
  [8.0227852e-04]
  [1.6134083e-03]


 48%|████▊     | 26/54 [17:08<18:20, 39.32s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[2.42524654e-01]
  [1.30579680e-01]
  [2.27964044e-01]
  [1.32732421e-01]
  [1.72454119e-02]
  [3.32344174e-02]
  [4.63403165e-02]
  [2.67226398e-02]
  [9.92712379e-03]
  [7.68125057e-02]
  [2.19556689e-03]
  [1.34113133e-02]
  [1.42077506e-02]
  [1.18054301e-01]
  [1.76324546e-02]
  [3.07342410e-03]
  [1.11746788e-03]
  [9.38874185e-02]
  [9.23181474e-02]
  [5.98262846e-02]
  [1.51357055e-03]
  [2.67847776e-02]
  [4.16341424e-03]
  [2.31089890e-01]
  [9.04176533e-02]
  [3.76990438e-03]
  [2.39138812e-01]
  [2.38664925e-01]
  [1.68012083e-02]
  [2.87830830e-03]
  [1.52737796e-02]
  [8.35454464e-03]
  [3.18697095e-03]
  [1.63120031e-03]
  [2.56606936e-03]
  [1.39918327e-02]
  [1.53228641e-03]
  [1.87247992e-04]
  [1.16893351e-02]
  [3.38855386e-03]
  [5.11273742e-03]
  [3.86002362e-02]
  [6.66821003e-03]
  [1.48138404e-03]
  [6.58401

 50%|█████     | 27/54 [17:47<17:40, 39.27s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[1.22839272e-01]
  [1.39644772e-01]
  [5.98898411e-01]
  [4.38603461e-02]
  [1.08814538e-02]
  [2.61333585e-03]
  [1.13485157e-02]
  [1.69909000e-02]
  [4.62090969e-03]
  [1.61142141e-01]
  [3.60816717e-04]
  [2.40567327e-03]
  [3.39525938e-03]
  [9.87218618e-02]
  [3.30494940e-02]
  [7.25121499e-05]
  [2.24649906e-04]
  [1.68276131e-02]
  [7.68046677e-02]
  [2.92094350e-02]
  [2.87085772e-04]
  [1.98683143e-03]
  [2.82022357e-03]
  [4.20525372e-02]
  [6.46325946e-03]
  [3.56426835e-03]
  [3.53950858e-02]
  [1.37346804e-01]
  [9.86963511e-04]
  [5.46059012e-03]
  [1.88784420e-01]
  [3.96162271e-04]
  [1.14688497e-04]
  [4.27186489e-04]
  [2.87255645e-03]
  [2.00978220e-02]
  [9.43487883e-03]
  [1.19026517e-04]
  [5.87521195e-02]
  [1.93712115e-03]
  [6.65854514e-02]
  [9.34380293e-03]
  [3.99568677e-03]
  [5.27828932e-04]
  [1.48594

 52%|█████▏    | 28/54 [18:26<17:01, 39.30s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[0.03606427]
  [0.21628451]
  [0.40579414]
  [0.07623824]
  [0.03862366]
  [0.03971845]
  [0.12683487]
  [0.06720379]
  [0.03548333]
  [0.09971786]
  [0.01708916]
  [0.0226512 ]
  [0.05063868]
  [0.22193095]
  [0.03756872]
  [0.00979486]
  [0.03364339]
  [0.16756332]
  [0.22875229]
  [0.07279643]
  [0.03043434]
  [0.46840143]
  [0.01630685]
  [0.3957625 ]
  [0.637556  ]
  [0.01780814]
  [0.38748762]
  [0.45909473]
  [0.32191962]
  [0.04225388]
  [0.02660453]
  [0.01390538]
  [0.01602253]
  [0.01397532]
  [0.02159238]
  [0.01954186]
  [0.01101872]
  [0.00344539]
  [0.01986909]
  [0.01066482]
  [0.01185489]
  [0.05263907]
  [0.03143111]
  [0.00715768]
  [0.01094407]
  [0.01725027]
  [0.01469091]
  [0.01907676]
  [0.08440742]
  [0.05883792]
  [0.06953827]
  [0.01210928]
  [0.04373354]
  [0.05431142]
  [0.03941521]
  [0.02247363]
  [0.0

 54%|█████▎    | 29/54 [19:06<16:27, 39.49s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[0.1242559 ]
  [0.23521242]
  [0.57161087]
  [0.0777587 ]
  [0.03465834]
  [0.0225777 ]
  [0.2055715 ]
  [0.2078523 ]
  [0.04833826]
  [0.20811644]
  [0.01376241]
  [0.14004943]
  [0.06388536]
  [0.17130312]
  [0.04215834]
  [0.02059913]
  [0.00858924]
  [0.09854859]
  [0.07878393]
  [0.26132643]
  [0.00849503]
  [0.05903527]
  [0.01346144]
  [0.20678976]
  [0.12040934]
  [0.01465797]
  [0.1378445 ]
  [0.3767932 ]
  [0.10736841]
  [0.02603033]
  [0.07528332]
  [0.057008  ]
  [0.1903964 ]
  [0.02034712]
  [0.05552414]
  [0.05162665]
  [0.01413086]
  [0.00337854]
  [0.02870438]
  [0.03891376]
  [0.01885787]
  [0.02906564]
  [0.00639701]
  [0.01969558]
  [0.05197442]
  [0.02168211]
  [0.01741514]
  [0.01129216]
  [0.0560863 ]
  [0.04409152]
  [0.05052572]
  [0.01900277]
  [0.04281265]
  [0.01504508]
  [0.03875533]
  [0.02649868]
  [0.0

 56%|█████▌    | 30/54 [19:47<15:55, 39.82s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[4.3343198e-01]
  [9.3418121e-02]
  [1.7472523e-01]
  [3.3016354e-02]
  [7.7210069e-03]
  [6.7449808e-03]
  [4.3264091e-02]
  [9.0374410e-02]
  [2.1484792e-03]
  [4.7209978e-02]
  [1.0401905e-03]
  [1.2446731e-02]
  [9.9557042e-03]
  [1.0992333e-01]
  [9.3505681e-03]
  [3.5236776e-03]
  [2.5391579e-04]
  [3.3186525e-02]
  [2.2598445e-02]
  [7.5553089e-02]
  [3.3953786e-04]
  [3.5449952e-02]
  [5.9249103e-03]
  [8.9966208e-02]
  [4.6121389e-02]
  [5.6891143e-03]
  [9.6588790e-02]
  [1.7441732e-01]
  [1.8401116e-02]
  [2.0750165e-03]
  [1.8321574e-02]
  [2.6828974e-02]
  [9.4451845e-02]
  [5.8270991e-03]
  [1.5054733e-02]
  [5.9332252e-03]
  [1.5205443e-02]
  [3.6722422e-04]
  [3.3225596e-02]
  [1.0622859e-02]
  [1.5045822e-02]
  [1.7401695e-02]
  [1.2752414e-03]
  [4.8727095e-03]
  [8.5105300e-03]
  [3.9350390e-03]
  [4.3229759e-03]


 57%|█████▋    | 31/54 [20:30<15:43, 41.02s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[5.07382751e-02]
  [4.20856863e-01]
  [8.90510857e-01]
  [1.13297820e-01]
  [1.30942166e-01]
  [8.67728591e-02]
  [5.28132021e-01]
  [4.01757479e-01]
  [8.59547257e-02]
  [2.91497946e-01]
  [2.08495855e-02]
  [9.16092098e-02]
  [9.47142541e-02]
  [5.03921270e-01]
  [5.04482090e-02]
  [1.33847594e-02]
  [2.73942947e-04]
  [2.25273967e-02]
  [7.39201605e-02]
  [4.79504585e-01]
  [3.61025333e-04]
  [4.86010313e-03]
  [5.27999997e-02]
  [5.77307343e-02]
  [1.44023895e-02]
  [5.26220500e-02]
  [5.61339259e-02]
  [1.64676756e-01]
  [6.09207153e-03]
  [1.33436620e-02]
  [3.42633426e-02]
  [4.28479016e-02]
  [2.37567812e-01]
  [4.10038233e-03]
  [8.75085592e-03]
  [2.13550031e-02]
  [1.07429624e-02]
  [1.47042572e-02]
  [5.38418889e-02]
  [1.63585842e-01]
  [2.09415555e-02]
  [4.85852361e-02]
  [2.29591131e-03]
  [2.11451828e-01]
  [1.77323

 59%|█████▉    | 32/54 [21:10<14:54, 40.64s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[0.1218437 ]
  [0.20323732]
  [0.40615782]
  [0.06174368]
  [0.04132843]
  [0.0243865 ]
  [0.15061373]
  [0.08130908]
  [0.05747452]
  [0.10840535]
  [0.01164827]
  [0.06851432]
  [0.07680288]
  [0.14273861]
  [0.03927472]
  [0.00903487]
  [0.00518623]
  [0.05556363]
  [0.09222507]
  [0.10952404]
  [0.00476012]
  [0.12722471]
  [0.00962102]
  [0.17275271]
  [0.1567297 ]
  [0.0087842 ]
  [0.17226303]
  [0.38195798]
  [0.45744103]
  [0.04162711]
  [0.01820695]
  [0.02071887]
  [0.09152097]
  [0.07180303]
  [0.06151736]
  [0.02385497]
  [0.02335519]
  [0.00336638]
  [0.01615304]
  [0.02648649]
  [0.01245552]
  [0.02988118]
  [0.00960395]
  [0.01728678]
  [0.01810277]
  [0.02546784]
  [0.02058822]
  [0.00775683]
  [0.03957546]
  [0.06063867]
  [0.04614884]
  [0.01345384]
  [0.02303684]
  [0.01065573]
  [0.04626805]
  [0.01878369]
  [0.0

 61%|██████    | 33/54 [21:50<14:09, 40.43s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[6.14337206e-01]
  [6.93745315e-02]
  [6.88413680e-02]
  [3.13691497e-02]
  [1.27083063e-02]
  [4.69756126e-03]
  [1.08781159e-02]
  [3.41361761e-03]
  [2.33408809e-03]
  [8.04847479e-03]
  [5.30689955e-04]
  [1.01791620e-02]
  [1.10045075e-02]
  [2.69442201e-02]
  [7.75963068e-03]
  [1.78381801e-03]
  [3.26125810e-05]
  [4.03039455e-02]
  [2.25508809e-02]
  [5.17788529e-03]
  [5.06434153e-05]
  [7.67573714e-03]
  [6.52760267e-03]
  [9.18380320e-02]
  [1.46442950e-02]
  [5.24771214e-03]
  [9.20200348e-02]
  [9.42807794e-02]
  [9.77194309e-03]
  [1.03321671e-03]
  [2.22307444e-03]
  [1.85173750e-03]
  [1.74609423e-02]
  [1.19262934e-03]
  [8.75854492e-03]
  [2.89124250e-03]
  [1.50591135e-04]
  [7.46756486e-05]
  [1.32843852e-03]
  [9.12815332e-04]
  [3.29822302e-04]
  [1.55394077e-02]
  [1.38992071e-03]
  [4.97132540e-04]
  [1.64315

 63%|██████▎   | 34/54 [22:30<13:24, 40.20s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[8.7294716e-01]
  [5.4780543e-02]
  [2.5260866e-02]
  [3.7648380e-03]
  [6.3802302e-03]
  [1.0439456e-03]
  [1.9340485e-02]
  [2.2505522e-03]
  [6.7910552e-04]
  [5.3264499e-03]
  [1.8885732e-04]
  [3.2247603e-03]
  [1.0552704e-03]
  [1.7176718e-02]
  [5.8020949e-03]
  [4.3568015e-04]
  [2.8064871e-06]
  [1.9612610e-03]
  [7.2361529e-03]
  [3.7813187e-03]
  [3.3455813e-06]
  [4.7805905e-04]
  [3.0530393e-03]
  [3.3653378e-03]
  [1.4499128e-03]
  [3.5267174e-03]
  [9.3302429e-03]
  [2.4960130e-02]
  [1.1611342e-02]
  [7.3695183e-04]
  [9.6768141e-04]
  [1.4469028e-03]
  [2.9746890e-03]
  [1.0786057e-03]
  [2.7711689e-03]
  [8.5562468e-04]
  [1.3407469e-03]
  [2.6354194e-04]
  [3.3690631e-03]
  [1.7618239e-03]
  [9.3895197e-04]
  [9.0261698e-03]
  [2.3508072e-03]
  [1.8024445e-04]
  [3.0553639e-03]
  [1.3906956e-03]
  [2.6949942e-03]


 65%|██████▍   | 35/54 [23:10<12:42, 40.13s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[8.8838255e-01]
  [3.3488244e-02]
  [2.7114213e-02]
  [8.6113513e-03]
  [8.1771612e-03]
  [1.9988716e-03]
  [1.4269412e-02]
  [1.1431575e-03]
  [2.5168061e-03]
  [6.7448914e-03]
  [3.0326843e-04]
  [7.2697401e-03]
  [2.7640462e-03]
  [1.0675341e-02]
  [5.2711070e-03]
  [6.6834688e-04]
  [1.3538670e-06]
  [4.4195354e-03]
  [9.7897351e-03]
  [3.1898320e-03]
  [1.8924504e-06]
  [3.3688545e-04]
  [2.5795698e-03]
  [7.5493753e-03]
  [1.0673702e-03]
  [2.0768344e-03]
  [1.3375878e-02]
  [2.1931082e-02]
  [8.0657303e-03]
  [5.4779649e-04]
  [8.8995695e-04]
  [1.0694265e-03]
  [5.1454902e-03]
  [1.2343824e-03]
  [2.9000938e-03]
  [1.4843941e-03]
  [2.3993850e-04]
  [1.5729666e-04]
  [1.4769137e-03]
  [9.2858076e-04]
  [3.0025840e-04]
  [9.0343356e-03]
  [3.0030608e-03]
  [1.7160177e-04]
  [2.1789074e-03]
  [8.7806582e-04]
  [1.6318560e-03]


 67%|██████▋   | 36/54 [23:49<11:59, 39.96s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[0.02747592]
  [0.30491242]
  [0.669356  ]
  [0.07647029]
  [0.0815616 ]
  [0.05436063]
  [0.31059206]
  [0.18298426]
  [0.03774276]
  [0.1638363 ]
  [0.02897722]
  [0.02847585]
  [0.04561654]
  [0.52057016]
  [0.08285248]
  [0.01643321]
  [0.09617689]
  [0.10448489]
  [0.22415614]
  [0.2189922 ]
  [0.07741803]
  [0.28253496]
  [0.01993611]
  [0.19884571]
  [0.5416504 ]
  [0.02196854]
  [0.23606989]
  [0.41291925]
  [0.24402645]
  [0.10298282]
  [0.10510123]
  [0.05529588]
  [0.01094887]
  [0.00987864]
  [0.01548207]
  [0.04686052]
  [0.03969678]
  [0.01094678]
  [0.05614659]
  [0.03867409]
  [0.04000893]
  [0.09227967]
  [0.05418196]
  [0.0171729 ]
  [0.0389055 ]
  [0.06833959]
  [0.05133358]
  [0.04944882]
  [0.29538387]
  [0.06409556]
  [0.12315008]
  [0.03766781]
  [0.0882293 ]
  [0.15941358]
  [0.03414351]
  [0.05454096]
  [0.0

 69%|██████▊   | 37/54 [24:29<11:17, 39.85s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[4.16058302e-03]
  [6.40701652e-01]
  [8.42793405e-01]
  [1.72230005e-02]
  [1.15912855e-02]
  [1.48671865e-02]
  [2.68723309e-01]
  [4.11337137e-01]
  [3.47618163e-02]
  [7.41772294e-01]
  [6.65295124e-03]
  [2.00842917e-02]
  [2.43891180e-02]
  [4.93240625e-01]
  [4.32881117e-02]
  [2.76798010e-03]
  [4.36064601e-03]
  [2.09766626e-02]
  [7.70398676e-02]
  [6.31097555e-01]
  [5.63928485e-03]
  [1.88927948e-02]
  [1.41933590e-01]
  [6.25306368e-02]
  [9.72847939e-02]
  [1.15430385e-01]
  [1.16751790e-01]
  [2.89725691e-01]
  [3.55261266e-02]
  [1.09075308e-02]
  [1.28282458e-01]
  [3.91652584e-02]
  [1.70103014e-02]
  [1.75649822e-02]
  [2.75015831e-03]
  [1.66862905e-02]
  [9.70508456e-01]
  [3.70870233e-02]
  [3.75241607e-01]
  [3.46910417e-01]
  [2.56673753e-01]
  [3.33487988e-02]
  [3.74636054e-03]
  [7.85799623e-02]
  [4.36321

 70%|███████   | 38/54 [25:09<10:37, 39.85s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[0.03918475]
  [0.2896939 ]
  [0.7993952 ]
  [0.26369822]
  [0.09259826]
  [0.06923079]
  [0.18800315]
  [0.1240488 ]
  [0.0456889 ]
  [0.27972758]
  [0.01500338]
  [0.03543377]
  [0.06205603]
  [0.33245632]
  [0.09258935]
  [0.00402862]
  [0.01464358]
  [0.14975473]
  [0.26524872]
  [0.17137626]
  [0.01806074]
  [0.09467956]
  [0.0119361 ]
  [0.32020703]
  [0.26446646]
  [0.0092735 ]
  [0.2635765 ]
  [0.29830176]
  [0.00793061]
  [0.02715445]
  [0.09385511]
  [0.00618637]
  [0.00523579]
  [0.00322735]
  [0.01646045]
  [0.09176356]
  [0.00759366]
  [0.00215819]
  [0.06278324]
  [0.01704761]
  [0.03994265]
  [0.04005736]
  [0.00761494]
  [0.01169208]
  [0.02798706]
  [0.07830203]
  [0.0429548 ]
  [0.04100433]
  [0.2847587 ]
  [0.17147687]
  [0.09480831]
  [0.07012078]
  [0.07766899]
  [0.4017269 ]
  [0.0530794 ]
  [0.08664557]
  [0.0

 72%|███████▏  | 39/54 [25:48<09:56, 39.74s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[7.3729610e-01]
  [5.9668273e-02]
  [4.5063138e-02]
  [2.2517174e-02]
  [3.0322522e-02]
  [3.1264126e-03]
  [1.7019033e-02]
  [3.6977530e-03]
  [1.7451346e-03]
  [8.1996024e-03]
  [3.4391880e-04]
  [3.2573938e-03]
  [6.2544048e-03]
  [3.2570302e-02]
  [6.8810284e-03]
  [7.0348382e-04]
  [3.1715244e-05]
  [1.0325462e-02]
  [1.7414689e-02]
  [2.9771924e-03]
  [3.4932877e-05]
  [7.2413385e-03]
  [5.1183999e-03]
  [3.9058745e-02]
  [1.1563450e-02]
  [4.2710602e-03]
  [5.6493878e-02]
  [6.4692616e-02]
  [6.3536763e-03]
  [1.3223290e-03]
  [1.2403429e-03]
  [9.8040700e-04]
  [4.2700768e-03]
  [1.4513135e-03]
  [6.6792071e-03]
  [3.0034781e-03]
  [4.8610568e-04]
  [2.2608042e-04]
  [3.4207404e-03]
  [1.2293458e-03]
  [9.3713403e-04]
  [6.0236454e-03]
  [2.1733344e-03]
  [6.6545606e-04]
  [2.1648109e-03]
  [2.9712021e-03]
  [3.2188892e-03]


 74%|███████▍  | 40/54 [26:28<09:15, 39.67s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[0.02310655]
  [0.45456478]
  [0.83117706]
  [0.08207631]
  [0.05229837]
  [0.03125608]
  [0.46607274]
  [0.36015606]
  [0.18167788]
  [0.6510691 ]
  [0.04704502]
  [0.05459711]
  [0.08795959]
  [0.40412143]
  [0.03044689]
  [0.00930405]
  [0.00770617]
  [0.05755472]
  [0.12021208]
  [0.43807745]
  [0.00873902]
  [0.0167942 ]
  [0.12541658]
  [0.10666767]
  [0.07783198]
  [0.12178215]
  [0.10684332]
  [0.30052817]
  [0.04721001]
  [0.03364843]
  [0.13681811]
  [0.01818106]
  [0.00941312]
  [0.02066231]
  [0.01384845]
  [0.0831762 ]
  [0.32477978]
  [0.04034433]
  [0.27337593]
  [0.16873631]
  [0.27051312]
  [0.04134721]
  [0.03001866]
  [0.06030053]
  [0.07762882]
  [0.10549828]
  [0.06745335]
  [0.06678721]
  [0.10267177]
  [0.09811911]
  [0.1598643 ]
  [0.02481294]
  [0.30775923]
  [0.17613682]
  [0.03117484]
  [0.05998167]
  [0.0

 76%|███████▌  | 41/54 [27:08<08:38, 39.87s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[9.8422456e-01]
  [6.9759786e-03]
  [1.6326904e-03]
  [9.3036890e-04]
  [1.2776852e-03]
  [1.7049909e-04]
  [1.2680292e-03]
  [4.1894673e-05]
  [4.8051770e-05]
  [2.4640560e-04]
  [2.7121882e-06]
  [1.0832238e-04]
  [1.0082727e-04]
  [1.6817749e-03]
  [6.9686770e-04]
  [2.8304161e-05]
  [7.1961881e-10]
  [3.6284328e-04]
  [1.1527240e-03]
  [7.5036798e-05]
  [1.1296258e-09]
  [7.3172050e-06]
  [7.9336762e-04]
  [7.7536702e-04]
  [1.5947973e-05]
  [6.6539645e-04]
  [2.7985871e-03]
  [2.2285283e-03]
  [1.6152859e-04]
  [1.0781886e-05]
  [1.6902299e-05]
  [1.5131181e-05]
  [2.7289987e-04]
  [3.4686193e-05]
  [3.3488870e-04]
  [6.8672249e-05]
  [1.0805201e-05]
  [5.0689587e-06]
  [1.9839406e-04]
  [3.8366699e-05]
  [2.0470885e-05]
  [8.2010031e-04]
  [2.1800399e-04]
  [3.4146169e-06]
  [7.7630248e-05]
  [2.5727495e-05]
  [7.0956543e-05]


 78%|███████▊  | 42/54 [27:50<08:05, 40.49s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[7.0102489e-01]
  [4.3430209e-02]
  [7.9521388e-02]
  [3.4760237e-02]
  [1.3981521e-02]
  [8.6354315e-03]
  [1.2457818e-02]
  [5.4982901e-03]
  [3.0042231e-03]
  [1.0584712e-02]
  [1.9547343e-04]
  [5.4689646e-03]
  [6.6050887e-03]
  [4.2069823e-02]
  [5.5959821e-03]
  [9.0405345e-04]
  [2.4794954e-06]
  [1.2841374e-02]
  [1.3458520e-02]
  [1.1016369e-02]
  [3.6636077e-06]
  [1.0558665e-03]
  [5.6513846e-03]
  [4.2951226e-02]
  [2.2136867e-03]
  [4.1380823e-03]
  [5.2334398e-02]
  [4.5306891e-02]
  [6.3607097e-04]
  [2.4172664e-04]
  [1.9042194e-03]
  [8.9591742e-04]
  [7.8501105e-03]
  [3.3998489e-04]
  [2.0579994e-03]
  [2.8511286e-03]
  [8.2333638e-05]
  [5.9439149e-05]
  [1.9052327e-03]
  [9.8815560e-04]
  [4.5597553e-04]
  [4.9616694e-03]
  [1.6805232e-03]
  [8.5467100e-04]
  [2.1988451e-03]
  [4.7215819e-04]
  [8.4108114e-04]


 80%|███████▉  | 43/54 [28:28<07:17, 39.73s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[1.18701696e-01]
  [1.51220500e-01]
  [2.47536659e-01]
  [2.69048214e-02]
  [1.38275325e-02]
  [6.80556893e-03]
  [2.28647292e-02]
  [2.29444504e-02]
  [7.83991814e-03]
  [4.36324775e-02]
  [5.47370315e-03]
  [4.38367128e-02]
  [4.20234501e-02]
  [4.63182628e-02]
  [1.73717439e-02]
  [3.15752625e-03]
  [5.73170185e-03]
  [1.24512613e-01]
  [8.05626214e-02]
  [2.25480199e-02]
  [7.05352426e-03]
  [3.60513389e-01]
  [1.60928071e-02]
  [3.41664314e-01]
  [4.06609476e-01]
  [1.66714489e-02]
  [2.39975899e-01]
  [4.08241451e-01]
  [3.63434136e-01]
  [2.18021572e-02]
  [1.92697048e-02]
  [8.98826122e-03]
  [7.77674913e-02]
  [2.43257284e-02]
  [8.98852348e-02]
  [6.96909428e-03]
  [2.59143114e-03]
  [5.10126352e-04]
  [4.37226892e-03]
  [2.68477201e-03]
  [2.64546275e-03]
  [2.37077773e-02]
  [1.24675035e-02]
  [2.69988179e-03]
  [3.04335

 81%|████████▏ | 44/54 [29:06<06:33, 39.32s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[7.21546292e-01]
  [7.84267485e-02]
  [8.57464671e-02]
  [2.76486278e-02]
  [1.35150254e-02]
  [4.14338708e-03]
  [1.68099403e-02]
  [4.34663892e-03]
  [4.08789515e-03]
  [4.25852537e-02]
  [2.88009644e-04]
  [2.51179934e-03]
  [5.01045585e-03]
  [3.97428274e-02]
  [8.62142444e-03]
  [4.02241945e-04]
  [8.39811037e-06]
  [8.03235173e-03]
  [1.78926885e-02]
  [1.14493966e-02]
  [1.31834613e-05]
  [6.28799200e-04]
  [2.80371308e-03]
  [1.84528232e-02]
  [2.22057104e-03]
  [2.20623612e-03]
  [2.61214674e-02]
  [7.20497668e-02]
  [3.21084261e-03]
  [9.22709703e-04]
  [8.04713368e-03]
  [5.56766987e-04]
  [5.83350658e-04]
  [1.29073858e-03]
  [1.71464682e-03]
  [7.72994757e-03]
  [2.46453285e-03]
  [1.21502424e-04]
  [1.38538480e-02]
  [1.61200762e-03]
  [1.15477741e-02]
  [1.16389692e-02]
  [3.75568867e-03]
  [4.21017408e-04]
  [3.22622

 83%|████████▎ | 45/54 [29:44<05:50, 38.92s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[6.0649580e-01]
  [6.1548889e-02]
  [1.4318761e-01]
  [3.9113551e-02]
  [2.6006252e-02]
  [7.2720647e-03]
  [7.3962510e-03]
  [3.4011006e-03]
  [2.9973686e-03]
  [2.3731858e-02]
  [9.1309543e-05]
  [1.6307533e-03]
  [6.0285032e-03]
  [4.2128116e-02]
  [6.2920451e-03]
  [2.7936697e-04]
  [6.8463287e-06]
  [1.2984604e-02]
  [1.7861307e-02]
  [6.5414608e-03]
  [1.0728795e-05]
  [4.4372678e-04]
  [4.6840310e-03]
  [4.2170674e-02]
  [1.6315579e-03]
  [5.0967336e-03]
  [4.5566648e-02]
  [5.3136468e-02]
  [9.3318748e-05]
  [3.5116076e-04]
  [5.5853426e-03]
  [1.3369322e-04]
  [2.0185113e-04]
  [6.6206165e-05]
  [1.1680722e-03]
  [7.7055395e-03]
  [5.3108881e-05]
  [2.5866249e-05]
  [1.7643273e-03]
  [4.9394369e-04]
  [1.1337399e-03]
  [3.2773316e-03]
  [2.4490952e-03]
  [5.9008598e-04]
  [9.6815825e-04]
  [7.3274970e-04]
  [1.5153289e-03]


 85%|████████▌ | 46/54 [30:23<05:11, 38.95s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[3.37544978e-02]
  [3.06704402e-01]
  [4.48988676e-01]
  [1.40522778e-01]
  [1.15893364e-01]
  [4.48099077e-02]
  [1.09736949e-01]
  [4.40046787e-02]
  [1.87042356e-02]
  [5.96096516e-02]
  [1.24861896e-02]
  [2.22889483e-02]
  [4.34942842e-02]
  [2.40773499e-01]
  [5.50562143e-02]
  [1.30133033e-02]
  [5.17290831e-02]
  [1.69350743e-01]
  [2.55748749e-01]
  [5.02147079e-02]
  [4.84872758e-02]
  [3.47026408e-01]
  [4.45255339e-02]
  [4.31226552e-01]
  [4.96913910e-01]
  [3.84937823e-02]
  [4.23986465e-01]
  [2.46921062e-01]
  [3.49446833e-02]
  [2.71050036e-02]
  [3.11709642e-02]
  [2.07405090e-02]
  [1.42325461e-02]
  [2.83619761e-03]
  [2.38445699e-02]
  [3.40047479e-02]
  [2.08264589e-03]
  [2.51814723e-03]
  [7.10812211e-03]
  [6.36127591e-03]
  [2.65961885e-03]
  [4.99980748e-02]
  [1.32525265e-02]
  [8.65831971e-03]
  [6.68057

 87%|████████▋ | 47/54 [31:02<04:31, 38.84s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[0.02396229]
  [0.36055863]
  [0.76151466]
  [0.0422577 ]
  [0.06686464]
  [0.01578763]
  [0.28057793]
  [0.31038284]
  [0.07182157]
  [0.28807557]
  [0.0472666 ]
  [0.25444344]
  [0.13518769]
  [0.24738947]
  [0.06387371]
  [0.04435977]
  [0.20431843]
  [0.18867049]
  [0.1752587 ]
  [0.3686002 ]
  [0.22224343]
  [0.48619014]
  [0.0416064 ]
  [0.33263183]
  [0.6122456 ]
  [0.03718114]
  [0.25731796]
  [0.43437812]
  [0.32780874]
  [0.17387038]
  [0.1532265 ]
  [0.13364926]
  [0.44916832]
  [0.05260527]
  [0.26364368]
  [0.09831586]
  [0.0435755 ]
  [0.01700902]
  [0.03155696]
  [0.05451062]
  [0.02429467]
  [0.03497249]
  [0.01751822]
  [0.04336217]
  [0.05017462]
  [0.04912513]
  [0.03427076]
  [0.03575674]
  [0.08437115]
  [0.08212438]
  [0.04078019]
  [0.02025518]
  [0.05435914]
  [0.02255431]
  [0.09147805]
  [0.03319806]
  [0.0

 89%|████████▉ | 48/54 [31:41<03:52, 38.76s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[9.4338071e-01]
  [1.2191623e-02]
  [7.6406300e-03]
  [2.9271543e-03]
  [1.5332103e-03]
  [6.4295530e-04]
  [2.3051798e-03]
  [2.4503469e-04]
  [6.8348646e-04]
  [2.7920902e-03]
  [2.3188899e-05]
  [1.6159713e-03]
  [1.1787713e-03]
  [4.1734874e-03]
  [9.7534060e-04]
  [2.6157498e-04]
  [4.2988560e-08]
  [2.5712848e-03]
  [1.8878579e-03]
  [9.7212195e-04]
  [6.7437284e-08]
  [9.1386813e-05]
  [1.2472570e-03]
  [8.5637867e-03]
  [2.4989247e-04]
  [9.9459291e-04]
  [1.3394028e-02]
  [1.9810766e-02]
  [5.8472753e-03]
  [6.0598999e-05]
  [3.0797720e-04]
  [3.0460954e-04]
  [1.6255975e-03]
  [8.8202953e-04]
  [6.0892105e-04]
  [3.3238530e-04]
  [6.4010368e-05]
  [9.3339440e-06]
  [2.3078918e-04]
  [1.7198920e-04]
  [7.7707133e-05]
  [2.6502013e-03]
  [9.5584989e-04]
  [3.0475710e-05]
  [2.7886033e-04]
  [8.5129177e-05]
  [3.2895803e-04]


 91%|█████████ | 49/54 [32:19<03:13, 38.74s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[6.01607382e-01]
  [8.64768028e-02]
  [1.56383783e-01]
  [1.03979260e-01]
  [2.37793326e-02]
  [2.36302614e-02]
  [4.59983349e-02]
  [5.86809516e-02]
  [3.54787707e-03]
  [2.39668489e-02]
  [1.06024742e-03]
  [1.80079639e-02]
  [1.50835812e-02]
  [1.01450026e-01]
  [1.24135911e-02]
  [3.60184908e-03]
  [3.28056376e-05]
  [3.42741311e-02]
  [2.49300599e-02]
  [5.59496880e-02]
  [6.36650511e-05]
  [5.49194217e-03]
  [7.89147615e-03]
  [8.16682577e-02]
  [1.03158653e-02]
  [7.27441907e-03]
  [8.79018605e-02]
  [1.13283962e-01]
  [1.22210383e-03]
  [7.11381435e-04]
  [6.59471750e-03]
  [7.50282407e-03]
  [5.95706999e-02]
  [6.37710094e-04]
  [4.08262014e-03]
  [5.68208098e-03]
  [5.27352095e-04]
  [1.85310841e-04]
  [1.52875781e-02]
  [5.78293204e-03]
  [3.44979763e-03]
  [1.78072155e-02]
  [1.36953592e-03]
  [5.30046225e-03]
  [1.38722

 93%|█████████▎| 50/54 [32:58<02:35, 38.88s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[3.27273905e-02]
  [2.73584545e-01]
  [8.83183718e-01]
  [1.88049674e-02]
  [2.41366625e-02]
  [1.76967084e-02]
  [4.56729621e-01]
  [5.83787739e-01]
  [6.74123168e-02]
  [2.60061473e-01]
  [7.66885281e-03]
  [1.28338844e-01]
  [4.90548909e-02]
  [5.04713714e-01]
  [3.73472869e-02]
  [2.75462568e-02]
  [2.39461660e-04]
  [2.88681686e-02]
  [1.94073617e-02]
  [6.63333237e-01]
  [2.85714865e-04]
  [6.20201230e-03]
  [5.45233190e-02]
  [4.89482880e-02]
  [1.18258595e-02]
  [7.96038806e-02]
  [5.85441887e-02]
  [3.01774085e-01]
  [1.23385519e-01]
  [3.60949039e-02]
  [1.18563116e-01]
  [1.32339418e-01]
  [6.49261117e-01]
  [2.49049664e-02]
  [2.96477377e-02]
  [8.37519765e-03]
  [5.66993952e-02]
  [7.00795650e-03]
  [3.18067670e-02]
  [1.06475949e-01]
  [3.10445428e-02]
  [2.85387933e-02]
  [3.17457318e-03]
  [1.67937785e-01]
  [8.90371

 94%|█████████▍| 51/54 [33:37<01:56, 38.93s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[7.07241297e-01]
  [3.13352048e-02]
  [1.10209465e-01]
  [2.38924921e-02]
  [1.01162493e-02]
  [7.73623586e-03]
  [2.97942460e-02]
  [6.57132268e-03]
  [9.49981809e-03]
  [1.29117370e-02]
  [6.62088394e-04]
  [1.76154673e-02]
  [1.43923461e-02]
  [3.01927626e-02]
  [3.65763903e-03]
  [2.87145376e-03]
  [7.97389475e-07]
  [1.07620060e-02]
  [8.41188431e-03]
  [1.34737790e-02]
  [1.51139682e-06]
  [4.60475683e-04]
  [5.36012650e-03]
  [3.10250819e-02]
  [1.01846457e-03]
  [5.74490428e-03]
  [3.22758257e-02]
  [5.17220199e-02]
  [3.93110514e-03]
  [4.51385975e-04]
  [1.35731697e-03]
  [2.24754214e-03]
  [4.55254614e-02]
  [1.52853131e-03]
  [2.71004438e-03]
  [1.89384818e-03]
  [8.98088329e-05]
  [1.27941370e-04]
  [1.03056431e-03]
  [3.02454829e-03]
  [2.43484974e-04]
  [6.34744763e-03]
  [7.51256943e-04]
  [1.35770440e-03]
  [3.37716

 96%|█████████▋| 52/54 [34:16<01:17, 38.78s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[1.34725630e-01]
  [1.75674945e-01]
  [5.89438915e-01]
  [1.34177208e-02]
  [1.72325373e-02]
  [4.45777178e-03]
  [6.97792768e-02]
  [1.28815055e-01]
  [8.40896368e-03]
  [6.20614886e-02]
  [2.14675069e-03]
  [1.35275364e-01]
  [3.40109468e-02]
  [8.49686265e-02]
  [1.75580084e-02]
  [1.13714039e-02]
  [1.60422921e-03]
  [6.88012242e-02]
  [1.86589658e-02]
  [1.20028943e-01]
  [1.41319633e-03]
  [8.81081522e-02]
  [1.05319917e-02]
  [1.61683530e-01]
  [8.53255689e-02]
  [1.34149194e-02]
  [9.36676264e-02]
  [2.66475320e-01]
  [6.45201504e-02]
  [1.56446695e-02]
  [2.97480524e-02]
  [4.04227674e-02]
  [7.37583280e-01]
  [1.19570792e-02]
  [1.95296854e-01]
  [8.72275233e-03]
  [5.55604696e-03]
  [7.01040030e-04]
  [4.16228175e-03]
  [1.25098228e-02]
  [2.70292163e-03]
  [8.73419642e-03]
  [7.20769167e-04]
  [1.41993463e-02]
  [1.22008

 98%|█████████▊| 53/54 [34:54<00:38, 38.64s/it]

Print type of tags_predictions:  <class 'tensorflow.python.framework.ops.EagerTensor'>
tags Predictions shape:  (1, 105, 1)
tags Predictions:  tf.Tensor(
[[[7.4194431e-01]
  [7.5228095e-02]
  [8.7174118e-02]
  [1.9180566e-02]
  [3.3964932e-02]
  [5.8431029e-03]
  [8.1246048e-02]
  [7.2994530e-03]
  [9.0613663e-03]
  [1.7364353e-02]
  [1.7611384e-03]
  [1.5603483e-02]
  [1.4500082e-02]
  [5.2741945e-02]
  [6.1085224e-03]
  [2.8461516e-03]
  [3.0515539e-06]
  [3.2654405e-03]
  [1.1861503e-02]
  [1.2821645e-02]
  [5.3028689e-06]
  [4.2703748e-04]
  [1.2548804e-02]
  [9.2031360e-03]
  [1.4527738e-03]
  [1.2596965e-02]
  [1.7202497e-02]
  [3.6616445e-02]
  [5.0737858e-03]
  [8.8980794e-04]
  [1.2207031e-03]
  [2.8113127e-03]
  [1.5270114e-02]
  [1.7878413e-03]
  [2.0743608e-03]
  [2.9106438e-03]
  [6.9293380e-04]
  [1.2630522e-03]
  [3.6436319e-03]
  [1.0557979e-02]
  [8.9308619e-04]
  [1.2287676e-02]
  [2.2020340e-03]
  [2.3905635e-03]
  [1.3458371e-02]
  [1.9990504e-03]
  [3.0467808e-03]


100%|██████████| 54/54 [35:34<00:00, 39.53s/it]


In [14]:

print(actual)
print(predicted)


['startseq hypoinflation with lingular focal atelectasis.\r\nlung volumes are.  opacities are present in the angulate. no focal infiltrates. heart size normal.', 'startseq recurrent right pneumothorax, complete collapse of the right lung, near 100%. right-to-left mediastinal shift is present, suggesting  physiology.', 'startseq 1. small 3.3 mm right-sided pneumothorax.\r\nsmall 3.3 mm right-sided pneumothorax only visible on the left lateral decubitus film. left lung is clear. normal cardiac contour. no evidence of pleural effusion.', 'startseq no acute findings.\r\ncardiac and mediastinal contours are within normal limits. prior granulomatous disease. the lungs are otherwise clear. thoracic spondylosis. bilateral breast prostheses with  calcification.', 'startseq 1. clear lungs. no radiographic evidence of active tb.\r\ncardiac and mediastinal contours are unremarkable. pulmonary vascularity is within normal limits. no focal air space opacities, pleural effusion, or pneumothorax. ther

In [15]:
d = dict()
d["actual"] = actual
d["predicted"] = predicted

In [16]:
df = pd.DataFrame(d)


In [17]:
print(df)

                                               actual  \
0   startseq hypoinflation with lingular focal ate...   
1   startseq recurrent right pneumothorax, complet...   
2   startseq 1. small 3.3 mm right-sided pneumotho...   
3   startseq no acute findings.\r\ncardiac and med...   
4   startseq 1. clear lungs. no radiographic evide...   
5   startseq multifocal right-sided pneumonia.\r\n...   
6   startseq no acute cardiopulmonary disease..\r\...   
7   startseq 1. no acute radiographic cardiopulmon...   
8   startseq heart size is normal. stable dilated ...   
9   startseq 1. no acute cardiopulmonary disease.\...   
10  startseq no acute cardiopulmonary abnormality....   
11  startseq no acute cardiopulmonary abnormality....   
12  startseq stable chest x-, without acute cardio...   
13  startseq mild cardiomegaly. tortuous aorta. no...   
14  startseq no acute cardiopulmonary disease.\r\n...   
15  startseq no acute cardiopulmonary findings..\r...   
16  startseq comparison,. no su

In [18]:
csv_file_name = 'output.csv'

# Save the DataFrame to a CSV file
df.to_csv(csv_file_name, index=False)

In [19]:
/pickle_file_path="medical_word_embeddings\saved_embeddings.pickle"

TypeError: 'str' object is not callable

In [ ]:
with open(pickle_file_path,"rb") as file:
    word_embeddings=pickle.load(file)

In [ ]:
def get_sentence_embeddings(sentence, word_embeddings):
    words = sentence.lower().split()  # Assuming the words are lowercase in your word_embedding dictionary

    # Filter out words that are not in the word_embedding dictionary
    valid_words = [word for word in words if word in word_embeddings]

    if not valid_words:
        # If no valid words are found in the word_embedding dictionary, return a zero vector
        return np.zeros(len(word_embeddings[next(iter(word_embeddings))]))

    # Calculate the mean of word embeddings for the valid words
    embedding_matrix = [word_embeddings[word] for word in valid_words]
    sentence_embedding = np.mean(embedding_matrix, axis=0)

    return sentence_embedding

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
def calculate_cosine_similarity(ground_truth, predicted, word_embeddings):
    ground_truth_embedding = get_sentence_embeddings(ground_truth, word_embeddings)
    predicted_embedding = get_sentence_embeddings(predicted, word_embeddings)

    # Reshape the vectors to 2D arrays
    ground_truth_embedding = ground_truth_embedding.reshape(1, -1)
    predicted_embedding = predicted_embedding.reshape(1, -1)

    similarity_score = cosine_similarity(ground_truth_embedding, predicted_embedding)
    return similarity_score[0][0]


In [ ]:
similarity = calculate_cosine_similarity(target, pred,word_embeddings)

In [ ]:
print("Cosine Similarity: {}".format(similarity))

Cosine Similarity: 0.8981666986586262
